/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSPredicate, NSString;

@interface ASAssetQuery : NSObject
{
    BOOL _queriesLocalAssetInformationOnly;
    NSString *_assetType;
    NSPredicate *_predicate;
    NSArray *_results;
}

+ (id)queryPredicateForProperties:(id)arg1;
@property(retain, nonatomic) NSArray *results; // @synthesize results=_results;
@property(retain, nonatomic) NSPredicate *predicate; // @synthesize predicate=_predicate;
@property(copy, nonatomic) NSString *assetType; // @synthesize assetType=_assetType;
@property(nonatomic) BOOL queriesLocalAssetInformationOnly; // @synthesize queriesLocalAssetInformationOnly=_queriesLocalAssetInformationOnly;
- (void)stopQuery;
- (void)startQuery:(id)arg1;
- (id)runQueryAndReturnError:(id *)arg1;
- (void)dealloc;
- (id)initWithAssetType:(id)arg1;

@end

