/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoLibraryServices/PLCloudSharingJob.h>

@class NSDate, NSString;

@interface PLCloudSharingViewedStateChangeJob : PLCloudSharingJob
{
    BOOL _assetCollectionHasUnreadComments;
    NSDate *_assetCollectionLastViewedCommentDate;
    int _albumUnviewedAssetCount;
    NSString *_albumGUID;
    int _jobType;
    BOOL _albumHasUnseenContent;
    NSString *_assetCollectionGUID;
}

+ (void)setLastViewedCommentDate:(id)arg1 forAssetCollection:(id)arg2 inAlbum:(id)arg3;
+ (void)markAssetCollection:(id)arg1 asHavingUnreadComments:(BOOL)arg2 inAlbum:(id)arg3;
+ (void)updateUnviewedAssetCollectionCount:(int)arg1 forAlbum:(id)arg2;
+ (void)markAlbum:(id)arg1 asHavingUnseenContent:(BOOL)arg2;
@property(retain, nonatomic) NSString *assetCollectionGUID; // @synthesize assetCollectionGUID=_assetCollectionGUID;
@property(nonatomic) BOOL albumHasUnseenContent; // @synthesize albumHasUnseenContent=_albumHasUnseenContent;
@property(nonatomic) int jobType; // @synthesize jobType=_jobType;
@property(retain, nonatomic) NSString *albumGUID; // @synthesize albumGUID=_albumGUID;
@property(nonatomic) int albumUnviewedAssetCount; // @synthesize albumUnviewedAssetCount=_albumUnviewedAssetCount;
@property(retain, nonatomic) NSDate *assetCollectionLastViewedCommentDate; // @synthesize assetCollectionLastViewedCommentDate=_assetCollectionLastViewedCommentDate;
@property(nonatomic) BOOL assetCollectionHasUnreadComments; // @synthesize assetCollectionHasUnreadComments=_assetCollectionHasUnreadComments;
- (void)_executeAssetLastViewedCommentDateChangedWithGroup;
- (void)_executeAssetCommentsReadStateChangedWithGroup;
- (void)_executeAlbumUnviewedAssetCountChangedWithGroup;
- (void)_executeAlbumViewedStateChanged;
- (void)runDaemonSide;
- (void)run;
- (int)daemonOperation;
- (void)dealloc;
- (id)description;
- (id)initFromXPCObject:(id)arg1;
- (void)encodeToXPCObject:(id)arg1;

@end

