/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "GeolocationUpdateListener-Protocol.h"
#import "WebGeolocationProvider-Protocol.h"

@class GeolocationCoreLocationDelegate, NSTimer, WebGeolocationPosition;

@interface WebGeolocationProviderIOS : NSObject <WebGeolocationProvider, GeolocationUpdateListener>
{
    BOOL _shouldResetOnResume;
    HashSet_2803207d _registeredWebViews;
    BOOL _isSuspended;
    HashSet_2803207d _pendingInitialPositionWebView;
    HashMap_842a3805 _webViewsWaitingForCoreLocationStart;
    NSTimer *_sendLastPositionAsynchronouslyTimer;
    GeolocationCoreLocationDelegate *_geolocationCoreLocationDelegate;
    HashSet_2803207d _warmUpWebViews;
    HashSet_2803207d _trackedWebViews;
    WebGeolocationPosition *_lastPosition;
    BOOL _enableHighAccuracy;
}

+ (id)sharedGeolocationProvider;
@property(nonatomic) BOOL enableHighAccuracy; // @synthesize enableHighAccuracy=_enableHighAccuracy;
@property(retain, nonatomic) WebGeolocationPosition *lastPosition; // @synthesize lastPosition=_lastPosition;
@property(readonly, nonatomic) HashSet_2803207d trackedWebViews; // @synthesize trackedWebViews=_trackedWebViews;
@property(readonly, nonatomic) HashSet_2803207d warmUpWebViews; // @synthesize warmUpWebViews=_warmUpWebViews;
@property(retain, nonatomic) GeolocationCoreLocationDelegate *geolocationCoreLocationDelegate; // @synthesize geolocationCoreLocationDelegate=_geolocationCoreLocationDelegate;
@property(retain, nonatomic) NSTimer *sendLastPositionAsynchronouslyTimer; // @synthesize sendLastPositionAsynchronouslyTimer=_sendLastPositionAsynchronouslyTimer;
@property(readonly, nonatomic) HashMap_842a3805 webViewsWaitingForCoreLocationStart; // @synthesize webViewsWaitingForCoreLocationStart=_webViewsWaitingForCoreLocationStart;
@property(readonly, nonatomic) HashSet_2803207d pendingInitialPositionWebView; // @synthesize pendingInitialPositionWebView=_pendingInitialPositionWebView;
@property(nonatomic) BOOL isSuspended; // @synthesize isSuspended=_isSuspended;
@property(readonly, nonatomic) HashSet_2803207d registeredWebViews; // @synthesize registeredWebViews=_registeredWebViews;
@property(nonatomic) BOOL shouldResetOnResume; // @synthesize shouldResetOnResume=_shouldResetOnResume;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)resetGeolocation;
- (void)errorOccurred:(id)arg1;
- (void)handlePendingInitialPosition:(id)arg1;
- (void)positionChanged:(id)arg1;
- (void)geolocationDelegateUnableToStart;
- (void)geolocationDelegateStarted;
- (void)stopTrackingWebView:(id)arg1;
- (void)resume;
- (void)suspend;
- (void)cancelWarmUpForWebView:(id)arg1;
- (void)initializeGeolocationForWebView:(id)arg1 listener:(id)arg2;
- (void)unregisterWebView:(id)arg1;
- (void)registerWebView:(id)arg1;
- (void)stopCoreLocationDelegateIfNeeded;
- (void)startCoreLocationDelegate;
- (void)dealloc;

@end

