/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIActivityViewController.h"

@class NSArray, UIViewController;

@interface PLActivityViewController : UIActivityViewController
{
    int _idiom;
    int _mode;
    UIViewController *_referenceViewController;
    NSArray *_photosActivities;
    id <PLActivityViewControllerDelegate> _delegate;
}

+ (id)applicationActivitiesForMode:(int)arg1 interfaceIdiom:(int)arg2;
@property(nonatomic) id <PLActivityViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *photosActivities; // @synthesize photosActivities=_photosActivities;
@property(retain, nonatomic) UIViewController *referenceViewController; // @synthesize referenceViewController=_referenceViewController;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(nonatomic) int idiom; // @synthesize idiom=_idiom;
- (void)_cleanupWithSuccess:(BOOL)arg1;
- (BOOL)_shouldShowSystemActivity:(id)arg1;
- (void)_performActivity:(id)arg1;
- (void)setPublishingActivityDelegate:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)dealloc;
- (id)initWithManagedAssets:(id)arg1 forMode:(int)arg2 interfaceIdiom:(int)arg3;

@end

