/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface ImageStore : NSObject
{
}

+ (id)imageForIconKey:(id)arg1;
+ (struct CGImage *)cgImageFromImage:(id)arg1;
+ (id)imageForBaseStationWithProductID:(unsigned int)arg1 small:(BOOL)arg2 cropped:(BOOL)arg3;
+ (id)imageForInformationalDiagram:(unsigned int)arg1;
+ (id)imageNameForProductFamily:(unsigned int)arg1 small:(BOOL)arg2 cropped:(BOOL)arg3;
+ (id)imageNamed:(id)arg1 inBundle:(id)arg2 ofType:(id)arg3;
+ (id)imageNamed:(id)arg1 inBundle:(id)arg2;
+ (id)sharedImageStore;
+ (id)imageForDeviceByModel:(id)arg1;
+ (id)kitImageOfType:(int)arg1;

@end

