/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/AssistantSubUIViewController.h>

@class NetTopoMiniStaticLayout, UIActivityIndicatorView, UILabel, UIView;

@interface StepByStepUIViewController : AssistantSubUIViewController
{
    UIView *topoContainerView;
    UIView *topoView;
    NetTopoMiniStaticLayout *topoLayout;
    UIView *tableFooterContainerView;
    UIView *spinnerWithStatusBelowView;
    UILabel *spinnerWithStatusBelowLabel;
    UIActivityIndicatorView *spinnerWithStatusBelowSpinner;
    int sbsMode;
}

@property(nonatomic) int sbsMode; // @synthesize sbsMode;
@property(retain, nonatomic) UIActivityIndicatorView *spinnerWithStatusBelowSpinner; // @synthesize spinnerWithStatusBelowSpinner;
@property(retain, nonatomic) UILabel *spinnerWithStatusBelowLabel; // @synthesize spinnerWithStatusBelowLabel;
@property(retain, nonatomic) UIView *spinnerWithStatusBelowView; // @synthesize spinnerWithStatusBelowView;
@property(retain, nonatomic) UIView *tableFooterContainerView; // @synthesize tableFooterContainerView;
@property(retain, nonatomic) NetTopoMiniStaticLayout *topoLayout; // @synthesize topoLayout;
@property(retain, nonatomic) UIView *topoView; // @synthesize topoView;
@property(retain, nonatomic) UIView *topoContainerView; // @synthesize topoContainerView;
- (BOOL)updateUIStr1:(id)arg1 forTag1:(unsigned int)arg2 matchesStr2:(id)arg3 forTag2:(unsigned int)arg4;
- (void)stepByStepUpdateProgress:(id)arg1 forState:(int)arg2;
- (void)syncTopoUIForTarget:(id)arg1 andSource:(id)arg2 andNetwork:(id)arg3 connectionType:(id)arg4;
- (void)syncTopoUIForTargetProductID:(id)arg1 targetName:(id)arg2 sourceProductID:(id)arg3 sourceName:(id)arg4 networkName:(id)arg5 connectionType:(id)arg6;
- (id)syncTopoUIInLayer:(id)arg1 withLayout:(id)arg2 targetProductID:(id)arg3 targetName:(id)arg4 sourceProductID:(id)arg5 sourceName:(id)arg6 networkName:(id)arg7 connectionType:(id)arg8;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;

@end

