/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IUAccessorySplashViewController, UIImage;

@interface IUAccessoryEventHandler : NSObject
{
    IUAccessorySplashViewController *_splashViewController;
    unsigned int _wantsSplash:1;
    double _accessoryEventButtonDownTime;
    unsigned int _accessoryEventKeyHeldHandled:1;
    unsigned int _accessoryEventRepeatCount;
    unsigned int _accessoryKeyRepeatTimerActive:1;
    unsigned int _accessoryKeyTimerIsForKeyHeld:1;
    BOOL _handlingSimpleRemoteEvent;
}

+ (id)sharedInstance;
@property(readonly, nonatomic, getter=isHandlingSimpleRemoteEvent) BOOL handlingSimpleRemoteEvent; // @synthesize handlingSimpleRemoteEvent=_handlingSimpleRemoteEvent;
- (BOOL)_togglePlaybackWouldPlayMusicSoundController;
- (void)_switchToPlaylistContextForSpecifier:(id)arg1;
- (BOOL)_setupMusicSoundController;
- (void)_endHandlingSimpleRemoteEvent;
@property(readonly, nonatomic) BOOL wantsSplashView;
@property(retain, nonatomic) UIImage *splashViewImage;
- (void)showSplashView:(BOOL)arg1;
- (void)tearDownSplashView;
- (void)hideSplashView;
- (void)handleSimpleRemoteAction:(int)arg1 withContext:(int)arg2 trackID:(long long)arg3;
- (void)handleFastForwardEventWithSeconds:(double)arg1;
- (void)handleRewindEventWithSeconds:(double)arg1;
- (void)handleDownArrowEvent;
- (void)handleUpArrowEvent;
- (void)handleSelectEvent;
- (BOOL)acceptRemoteNavigationCommand;
- (BOOL)handleMenuEvent;
- (BOOL)handleRepeatAdvanceEvent;
- (BOOL)handleShuffleAdvanceEvent;
- (BOOL)handleTogglePlaybackEvent;
- (BOOL)handleStopEvent;
- (BOOL)_handleEventWithHandler:(SEL)arg1 ifCurrentItemType:(unsigned int)arg2;
- (BOOL)handleSeekEndEvent;
- (BOOL)handleSeekBeginEvent:(int)arg1;
- (BOOL)handlePlaylistSeek:(int)arg1;
- (BOOL)handlePlayEvent;
- (BOOL)handlePauseEvent;
- (BOOL)handleChangeTrackEvent:(int)arg1 deltaType:(int)arg2;
- (BOOL)handleChangeTrackEvent:(int)arg1;
- (BOOL)handleChangeChapterEvent:(int)arg1;
- (BOOL)handleAlbumSeek:(int)arg1;
@property(readonly, nonatomic, getter=isPlayingSingleMovie) BOOL playingSingleMovie;
@property(readonly, nonatomic, getter=isHandlingRemoteEvent) BOOL handlingRemoteEvent;
- (void)dealloc;
- (id)init;

@end

