/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class UIButton, UIImage, UIImageView, UILabel, UINavigationBar, UITabBar;

@interface IUAccessorySplashView : UIView
{
    unsigned int _imageIsExternal:1;
    UIImageView *_imageView;
    UILabel *_label;
    UINavigationBar *_navigationBar;
    UILabel *_routeNameLabel;
    UIButton *_routePickerButton;
    UITabBar *_tabBar;
}

- (id)_navBarTitle;
- (void)_availableRoutesChangedNotification:(id)arg1;
- (void)_routePickerButtonAction:(id)arg1;
@property(retain, nonatomic) UIImage *image;
- (void)setExternalImage:(id)arg1;
@property(readonly, nonatomic) UILabel *routeNameLabel;
@property(readonly, nonatomic) UIButton *routePickerButton;
- (void)layoutSubviews;
- (void)reloadRoutePickerAnimated:(BOOL)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

