/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class AVPlayer, MPDownloadProgressIndicator, NSObject<OS_dispatch_source>, UIImage, UIImageView;

@interface IUAudioPreviewView : UIView
{
    NSObject<OS_dispatch_source> *_animationTimer;
    UIImageView *_artworkImageView;
    AVPlayer *_AVPlayer;
    double _currentItemDuration;
    id <IUAudioPreviewViewDelegate> _delegate;
    MPDownloadProgressIndicator *_progressIndicator;
    UIImage *_artworkImage;
}

@property(nonatomic) id <IUAudioPreviewViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AVPlayer *AVPlayer; // @synthesize AVPlayer=_AVPlayer;
@property(retain, nonatomic) UIImage *artworkImage; // @synthesize artworkImage=_artworkImage;
- (void)_stopAnimating;
- (void)_startAnimating;
- (void)_setProgress:(float)arg1;
- (void)_cancelAnimationTimer;
- (void)flipToPreviewProgressAnimated:(BOOL)arg1 withCompletionHandler:(id)arg2;
- (void)flipFromPreviewProgressAnimated:(BOOL)arg1 withCompletionHandler:(id)arg2;
- (void)_cancelAction:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

