/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class IUMediaTableCell, IUTableCellConfiguration, NSMutableArray;

@interface IUMediaTableCellContentView : UIView
{
    struct CGSize _backgroundSize;
    IUMediaTableCell *_cell;
    IUTableCellConfiguration *_configuration;
    NSMutableArray *_configManagedSubviews;
    NSMutableArray *_subviews;
    unsigned int _drawAsDisabled:1;
    unsigned int _drawInAlternateStyle:1;
    unsigned int _editing:1;
    unsigned int _highlighted:1;
    unsigned int _selected:1;
    unsigned int _useSubviewLayout:1;
    unsigned int _hideArtwork:1;
}

@property(retain, nonatomic) IUTableCellConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) IUMediaTableCell *cell; // @synthesize cell=_cell;
@property(nonatomic) struct CGSize backgroundSize; // @synthesize backgroundSize=_backgroundSize;
- (id)_scriptingInfo;
- (BOOL)_useSubviewLayout;
- (void)_updateDisabledStyleForSubviews;
- (void)_stopUsingSubviewLayout;
- (void)_startUsingSubviewLayout;
- (void)_removeSubviewsForConfiguration;
- (void)_updateSubviewBackgrounds;
- (void)_reloadSubviewsForConfiguration;
- (void)_reloadSubviewAlphasAnimated:(BOOL)arg1;
- (void)_drawBackgroundInRect:(struct CGRect)arg1;
@property(nonatomic) BOOL hideArtwork;
@property(readonly, nonatomic) struct CGRect artworkFrame;
@property(nonatomic) BOOL drawInAlternateStyle;
@property(nonatomic, getter=isSelected) BOOL selected;
@property(nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)setFrame:(struct CGRect)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL drawAsDisabled;
@property(nonatomic, getter=isDeleteConfirmationVisible) BOOL deleteConfirmationVisible;
- (void)setConfigurationNeedsDisplay;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawContentInRect:(struct CGRect)arg1;
- (void)prepareForReuse;
- (void)dealloc;

@end

