/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ACDClient, NSDictionary, NSSet;

@interface ACDClientAuthorization : NSObject
{
    BOOL _isGranted;
    NSSet *_grantedPermissions;
    ACDClient *_client;
    NSDictionary *_options;
}

@property(retain, nonatomic) NSDictionary *options; // @synthesize options=_options;
@property(retain, nonatomic) ACDClient *client; // @synthesize client=_client;
@property(retain, nonatomic) NSSet *grantedPermissions; // @synthesize grantedPermissions=_grantedPermissions;
@property(nonatomic) BOOL isGranted; // @synthesize isGranted=_isGranted;
- (void).cxx_destruct;
- (id)initForClient:(id)arg1;

@end

